[{"ContainerToolsException.Message":"failed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 287\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 120\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 445\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:line 16\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 82","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"Network micro-app-network  Removing\r\nNetwork micro-app-network  Error\r\nfailed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints"},{"ContainerToolsException.Message":"failed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 287\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 120\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 445\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:line 16\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 82","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"Network micro-app-network  Removing\r\nNetwork micro-app-network  Error\r\nfailed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints"},{"ContainerToolsException.Message":"failed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 287\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 120\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 445\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:line 16\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 82","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"Network micro-app-network  Removing\r\nNetwork micro-app-network  Error\r\nfailed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints"},{"ContainerToolsException.Message":"failed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 287\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 120\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 445\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:line 16\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 82","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"Network micro-app-network  Removing\r\nNetwork micro-app-network  Error\r\nfailed to remove network micro-app-network: Error response from daemon: error while removing network: network micro-app-network id 92662c15a7ef45e3866919a6f2c55bb081b4125b66ae8416290c0c6bf5ffab96 has active endpoints"}]